### ISSUE TITLE
how to install packages on it?

### ISSUE THREAD

**Issue by youngplayer2017** [tilayealemu/dockerr#1]
I'm using this project as a Rserver, and I want to install some packages.
I've tried to send cmd like "install.packages(xxx)"  to it, and it running a long time, but returned null.
And then, when I try to use this library as "library(xxx)", it returns error "ERROR:org.rosuda.REngine.Rserve.RserveException: eval failed, request status: error code: 127". 
I think this method to install package failed.

Could you please tell me any other way to install packages in this project?

**Comment by tilayealemu** [comment]
Please post your full log.

**Comment by youngplayer2017** [comment]
I've found following errors in console during executing "install.packages('spdep')"

configure: error: in `/tmp/RtmpTR3yaY/R.INSTALL36120d588db/units':
configure: error: 
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
* removing ‘/usr/local/lib/R/site-library/units’
* installing *source* package ‘gdata’ ...
** package ‘gdata’ successfully unpacked and MD5 sums checked
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (gdata)
ERROR: dependency ‘raster’ is not available for package ‘spData’
* removing ‘/usr/local/lib/R/site-library/spData’
ERROR: dependency ‘units’ is not available for package ‘sf’
* removing ‘/usr/local/lib/R/site-library/sf’
* installing *source* package ‘gmodels’ ...
** package ‘gmodels’ successfully unpacked and MD5 sums checked
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (gmodels)
ERROR: dependencies ‘spData’, ‘sf’ are not available for package ‘spdep’
* removing ‘/usr/local/lib/R/site-library/spdep’

**Comment by youngplayer2017** [comment]
during executing "install.packages('RMySQL')"


* installing *source* package ‘RMySQL’ ...
** package ‘RMySQL’ successfully unpacked and MD5 sums checked
Using PKG_CFLAGS=
Using PKG_LIBS=-lmysqlclient
-----------------------------[ ANTICONF ]-----------------------------
Configure could not find suitable mysql/mariadb client library. Try installing:
 * deb: libmariadbclient-dev | libmariadb-client-lgpl-dev (Debian, Ubuntu)
 * rpm: mariadb-connector-c-devel | mariadb-devel | mysql-devel (Fedora, CentOS, RHEL)
 * csw: mysql56_dev (Solaris)
 * brew: mariadb-connector-c (OSX)
If you already have a mysql client library installed, verify that either
mariadb_config or mysql_config is on your PATH. If these are unavailable
you can also set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------[ ERROR MESSAGE ]----------------------------
<stdin>:1:19: fatal error: mysql.h: No such file or directory
compilation terminated.
-----------------------------------------------------------------------
ERROR: configuration failed for package ‘RMySQL’
* removing ‘/usr/local/lib/R/site-library/RMySQL’

The downloaded source packages are in
        ‘/tmp/RtmppbnwLa/downloaded_packages’

**Comment by tilayealemu** [comment]
I have added spdep for you ([diff](https://github.com/tilayealemu/dockerr/commit/1059b3d0c5e9c06b9ffc800eb1ebedbc545ae014#diff-ebacf6f6ae4ee68078bb16454b23247dR36)). Please try again. Since the image isn't versioned yet, you have to delete the cached image locally first:

    docker rmi -f tilayealemu/dockerr

Then re-run the container.

**Comment by youngplayer2017** [comment]
well, thank you! It does work.
But how about other libs?
 could you set it as params in docker file to enable user to add more other libs?

**Comment by tilayealemu** [comment]
There are a few ways to install other libraries. You can override entrypoint on the docker run command or login to the container to install your lib and restart it (if you need RServe to pick it up). Can also use tilayealemu/dockerr as your base image and have your own image, etc. Depends on your scenario.

**Comment by youngplayer2017** [comment]
I've got the following codes in docker file.
And I'm going to build docker image by this docker file after adding some other libs. 
But install2.r is not found in project, could you share it ?

RUN install2.r --error \
  -r "https://cran.rstudio.com" \
  Rserve \
  spdep

**Comment by tilayealemu** [comment]
Command install2.r is available (see also /usr/local/bin/install2.r). As much as I'd like to help, your query is outside the scope of this opensource project. Your problem can be solved by learning more about how to install packages in Linux systems, and how to us docker.

**Comment by tilayealemu** [comment]
Command install2.r is available (see also /usr/local/bin/install2.r). As much as I'd like to help, your query is outside the scope of this opensource project. Your problem can be solved by learning more about how to install packages in Linux systems, and how to us docker.

**Comment by youngplayer2017** [comment]
HI Tialye,
    Firstly, Thank you very much for your help.

    The problem's core cause is China's firewall which disabled the sources.list for apt-get. So I can't install libs for R , even I enter the docker to install.

 And I tried to change sources.list, but the following error occured!

 The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32

  When I tried to add public key, the "gnupg2" is needed for apt-key. So I've to install gnupg2 firstly。 but no avaliable source. It's a dead loop.
   So could you please relase a version for China which according to following dockerfile :

FROM rocker/r-base

MAINTAINER "Tilaye Yismaw" tilaye@gmail.com 

RUN apt-get install -y gnupg2 
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial main" >/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-updates main" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/ubuntu/ xenial universe" >>/etc/apt/sources.list && \
 echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-updates universe" >>/etc/apt/sources.list &&\
 echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-security universe" >>/etc/apt/sources.list &&\
 echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-security main" >>/etc/apt/sources.list 




RUN apt-get update && apt-get install -y \
  telnet \
  procps \
  lbzip2 \
  libfftw3-dev \
  libgdal-dev \
  libgeos-dev \
  libgsl0-dev \
  libgl1-mesa-dev \
  libglu1-mesa-dev \
  libhdf4-alt-dev \
  libhdf5-dev 

RUN apt-get update && apt-get install -y \
  libjq-dev \
  libpq-dev \
  libproj-dev \
  libprotobuf-dev \
  libnetcdf-dev \
  libsqlite3-dev \
  libssl-dev \
  libudunits2-dev \
  netcdf-bin \
  postgis \
  protobuf-compiler \
  sqlite3 \
  tk-dev \
  unixodbc-dev \
  libmariadb-client-lgpl-dev

RUN install2.r --error \
  -r "https://cran.rstudio.com" \
  Rserve \
  spdep \
  RMySQL \
  Ridit \
  pgirmess

RUN rm -rf /tmp/downloaded_packages/ /tmp/*.rds

EXPOSE 6311
ENTRYPOINT R -e "Rserve::run.Rserve(remote=TRUE)"



------------------------------------------------------------------
发件人：Tilaye Yismaw Alemu <notifications@github.com>
发送时间：2020年9月17日(星期四) 05:04
收件人：tilayealemu/dockerr <dockerr@noreply.github.com>
抄　送：youngplayer <youngplayer@aliyun.com>; Author <author@noreply.github.com>
主　题：Re: [tilayealemu/dockerr] how to install packages on it? (#1)

Command install2.r is available (see also /usr/local/bin/install2.r). As much as I'd like to help, your query is outside the scope of this opensource project. Your problem can be solved by learning more about how to install packages in Linux systems, and how to us docker.

**Comment by tilayealemu** [comment]
Your request is outside the scope of this project. Good luck.

**Comment by youngplayer2017** [comment]
Well, I fix it by entering docker and install packages in R platform. 


------------------------------------------------------------------
发件人：Tilaye Yismaw Alemu <notifications@github.com>
发送时间：2020年9月18日(星期五) 20:03
收件人：tilayealemu/dockerr <dockerr@noreply.github.com>
抄　送：youngplayer <youngplayer@aliyun.com>; Author <author@noreply.github.com>
主　题：Re: [tilayealemu/dockerr] how to install packages on it? (#1)

Your request is outside the scope of this project. Good luck.
